<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_script_include">
    <sys_script_include action="INSERT_OR_UPDATE">
        <access>public</access>
        <active>true</active>
        <api_name>x_snc_geodata.LogError</api_name>
        <caller_access>1</caller_access>
        <client_callable>false</client_callable>
        <description>Produces an error log output in the application log.</description>
        <name>LogError</name>
        <script><![CDATA[function LogError(vPayload)
{
	gs.error(x_snc_devtools.PrepareLogError(vPayload));
}]]></script>
        <sys_class_name>sys_script_include</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2024-03-10 11:10:27</sys_created_on>
        <sys_id>bebb4566db304a10f0f1d03cd39619e0</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>LogError</sys_name>
        <sys_package display_value="GeoData" source="x_snc_geodata">f9cb2003dbf6cd10bcced03cd396199e</sys_package>
        <sys_policy/>
        <sys_scope display_value="GeoData">f9cb2003dbf6cd10bcced03cd396199e</sys_scope>
        <sys_update_name>sys_script_include_bebb4566db304a10f0f1d03cd39619e0</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2024-03-10 11:10:27</sys_updated_on>
    </sys_script_include>
</record_update>
